GET http://localhost:1234/api/usuarios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjU2LCJyb2xlcyI6W3sibm9tYnJlIjoiQWRtaW4ifV0sInBlcm1pc29zIjp7ImVzY3JpdHVyYSI6dHJ1ZSwibGVjdHVyYSI6dHJ1ZX0sImlhdCI6MTcwMzc3MTYwNSwiZXhwIjoxNzAzNzc1MjA1fQ.LpV6DzV6jbe76tO7rHUp0CoH4_eopGHBNp5pghlvb_c
###
POST http://localhost:1234/api/login
Content-Type: application/json

{
  "nombre": "Rodrixd",
  "email": "rodrixd@ejemplo.com",
  "password": "1231231234567",
  "roles": ["Admin"],
  "permisos": {
    "escritura": true,
    "lectura": true
  }
}
###
POST http://localhost:1234/api/registro
Content-Type: application/json

{
  "nombre": "asdaaaaaasd",
  "email": "aaaa@444.com",
  "password": "123asdasd123123123",
  "roles": ["Admin"],
  "permisos": {
    "escritura": true,
    "lectura": true
  }
}
###
PUT http://localhost:1234/api/usuarios/42
Content-Type: application/json

{
  "nombre": "pepe",
  "email": "45prueba@ejemplo.com",
  "password": "1231231234567",
  "roles": ["Admin"],
  "permisos": {
    "escritura": true,
    "lectura": true
  }
}
###
PUT http://localhost:1234/api/usuarios/desactivar/18
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjU2LCJyb2xlcyI6W3sibm9tYnJlIjoiQWRtaW4ifV0sInBlcm1pc29zIjp7ImVzY3JpdHVyYSI6dHJ1ZSwibGVjdHVyYSI6dHJ1ZX0sImlhdCI6MTcwMzc3MTYwNSwiZXhwIjoxNzAzNzc1MjA1fQ.LpV6DzV6jbe76tO7rHUp0CoH4_eopGHBNp5pghlvb_c
###
PUT http://localhost:1234/api/usuarios/reactivar/18
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQzLCJyb2xlcyI6W3sibm9tYnJlIjoiQWRtaW4ifV0sInBlcm1pc29zIjp7ImVzY3JpdHVyYSI6dHJ1ZSwibGVjdHVyYSI6dHJ1ZX0sImlhdCI6MTcwMzcwOTA0MiwiZXhwIjoxNzAzNzEyNjQyfQ.MOxjbuBABFxdBGTYjaf0de69q9mz6B-9mDCdeguMVAw